version: '2.2'
services:
  tg-app-model-front:
    extends:
      file: docker-compose.yml
      service: tg-app-model-front
    build:
      args:
        - Authority=${STS_SERVER}
        - UseAuthority=${USE_AUTHORITY}
        - RequireHttpsMetadata=${USE_SSL}
        - ApiName=${API_NAME}
        - ImgFolder=~/images
        - HostServer=${HOST_SERVER}
        - HostPort=${HOST_PORT}
        - ApiUrl=${API_URL}
        - ClientId=${CLIENT_ID}
        - MapKey="your_google_map_key"
      dockerfile: Dockerfile
      context: ./Web
    networks:
      - tg-app-model-network

  tg-app-model-api:
    extends:
      file: docker-compose.yml
      service: tg-app-model-api
    build:
      args:
        - port=${API_PORT}
      dockerfile: Api/Dockerfile
      context: ./
    networks:
      - tg-app-model-network

networks:
  tg-app-model-network:
    driver: bridge
