@echo off
rem docker-machine start default
SET API_NAME=api1
SET HOST_PORT=4200
SET API_PORT=52050
SET API_URL=http://192.168.0.5:%API_PORT%/api/
SET IDENTITY_SERVER=https://192.168.0.5:5001
SET USE_SSL=true
SET HOST_SERVER=http://192.168.0.5
SET CLIENT_ID="tgappmodel"

SET API_NAME=api1
SET HOST_SERVER=http://192.168.0.5
SET HOST_PORT=4200
SET HOST_URL=%HOST_SERVER%:%HOST_PORT%
SET API_SERVER=http://192.168.0.5
SET API_PORT=52050
SET API_URL=%API_SERVER%:%API_PORT%/api/
SET IDENTITY_SERVER=https://192.168.0.5
SET IDENTITY_PORT=5001
SET IDENTITY_URL=%IDENTITY_SERVER%:%IDENTITY_PORT%
SET USE_SSL=true
SET CLIENT_ID="tgappmodel"

cd %~dp0
docker-compose build HOST_PORT=%HOST_PORT% API_PORT=%API_PORT% API_URL=%API_URL% API_NAME=%API_NAME% USE_SSL=%USE_SSL% IDENTITY_SERVER=%IDENTITY_SERVER% HOST_SERVER=%HOST_SERVER% CLIENT_ID=%CLIENT_ID%


docker-compose up -d HOST_PORT=%HOST_PORT% API_PORT=%API_PORT% API_URL=%API_URL% API_NAME=%API_NAME% USE_SSL=%USE_SSL% IDENTITY_SERVER=%IDENTITY_SERVER% HOST_SERVER=%HOST_SERVER% CLIENT_ID=%CLIENT_ID%

pause
start "http://localhost:%HOST_PORT%"
start "http://localhost:%HOST_PORT%/admin"
start "%API_SERVER%:%API_PORT%/swagger"